version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        USER: sammy
        UID: 1000
    container_name: api-app
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /var/www/vendor
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    depends_on:
      - db
    networks:
      - dockernet

  nginx:
    image: nginx:alpine
    container_name: api-nginx
    ports:
      - "9000:80"
      - "9443:443"
    volumes:
      - .:/var/www:delegated
      - ./docker/nginx/api.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/nginx/certs
    depends_on:
      - app
    networks:
      - dockernet

  db:
    image: mysql:8.0
    container_name: api-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_USER: ${DB_USERNAME}        # NOT root
      MYSQL_PASSWORD: ${DB_PASSWORD}    # password for that user
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - dockernet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: api-phpmyadmin
    depends_on:
      - db
    ports:
      - "9081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASSWORD_ROOT}
    networks:
      - dockernet

networks:
  dockernet:
    driver: bridge

volumes:
  mysql_data:
